version: 2
updates:
  - package-ecosystem: gradle
    directory: /projects/gradle-shared-config/
    schedule:
      interval: daily
    groups:
      dependencies:
        patterns:
          - '*'
    ignore:
      - dependency-name: org.junit.jupiter
        update-types:
          - version-update:semver-minor
          - version-update:semver-major
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      dependencies:
        patterns:
          - '*'
    ignore:
      - dependency-name: "actions/cache"
